name: Build STM32IDE Project

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  # enable manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/quanghainguyen/stm32-build:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # submodules too
          submodules: recursive

      - name: Build project
        run: |
          docker run --volume=${PWD}:\workdir\project ghcr.io/quanghainguyen/stm32-build:latest python3 stm32_build.py -b stm32ide

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: STM32F4_Sample.artifacts
          # The output artifacts are BLE_p2pServer.elf, BLE_p2pServer.map, etc.
          # Use a wildcard pattern to get them all
          path: project/Debug/STM32F4_Sample.*
